apiVersion: v1
kind: ServiceAccount
metadata:
  name: tank-sa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    tank: "true"
  labels:
    service: tank
    app: tank
  name: tank
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: tank
        app: tank
    spec:
      serviceAccountName: tank-sa
      containers:
        - name: tank
          image: mateuszbyczkowski/tank-game:v1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 300m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 1Gi
      nodeSelector:
        monitoring: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: tank-service
  labels:
    service: tank
    app: tank
spec:
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    service: tank

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: tank-sr
  namespace: jungle
spec:
  rules:
    - services: [
      "tank-service.{{ .Release.Namespace }}.svc.cluster.local"
    ]

---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-tank-sr
  namespace: jungle
spec:
  subjects:
    - properties:
        source.principal: "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
  roleRef:
    kind: ServiceRole
    name: "tank-sr"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-tank
spec:
  hosts:
    - tank.dev.payworks.io
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - port: 443
      route:
        - destination:
            port:
              number: 80
            host: tank-service
